version: '2.3'
services:
 screenshotr:
   build: .
   restart: always
   container_name: screenshotr
   environment:
     - Screenshotr:Data=/data
   volumes:
     - ./datatest:/data
   tty: true
   ports:
     - 5020:5020
