name: Linux

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'publish/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'publish/'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.103'
    - name: Build
      run: sh ./build.sh
